// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account.sql

package store

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (name, type, currency)
VALUES ($1, $2, $3)
RETURNING id, name, type, currency, archived, created_at
`

type CreateAccountParams struct {
	Name     string
	Type     string
	Currency string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.Type, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAccounts = `-- name: ListActiveAccounts :many
SELECT id, name, type, currency, archived, created_at
FROM account
WHERE NOT archived
ORDER BY name, id
`

func (q *Queries) ListActiveAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listActiveAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccounts = `-- name: ListAllAccounts :many
SELECT id, name, type, currency, archived, created_at
FROM account
ORDER BY archived, name, id
`

func (q *Queries) ListAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameAccount = `-- name: RenameAccount :execrows
UPDATE account SET name = $2 WHERE id = $1
`

type RenameAccountParams struct {
	ID   int64
	Name string
}

func (q *Queries) RenameAccount(ctx context.Context, arg RenameAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameAccount, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountArchived = `-- name: SetAccountArchived :execrows
UPDATE account SET archived = $2 WHERE id = $1
`

type SetAccountArchivedParams struct {
	ID       int64
	Archived bool
}

func (q *Queries) SetAccountArchived(ctx context.Context, arg SetAccountArchivedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountArchived, arg.ID, arg.Archived)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
