// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: analytics.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const listLedgerForAnalytics = `-- name: ListLedgerForAnalytics :many

SELECT
    t.type,
    t.occurred_on,
    CAST(CASE WHEN t.type = 'income' THEN t.to_amount ELSE t.from_amount END AS NUMERIC(19, 4)) AS amount,
    a.currency AS currency,
    c.name AS category_name
FROM transaction t
JOIN account a
    ON a.id = CASE WHEN t.type = 'income' THEN t.to_account_id ELSE t.from_account_id END
LEFT JOIN category c ON c.id = t.category_id
WHERE t.type IN ('income', 'expense')
    AND t.occurred_on >= $1
    AND t.occurred_on < $2
ORDER BY t.occurred_on, t.id
`

type ListLedgerForAnalyticsParams struct {
	OccurredOn   time.Time
	OccurredOn_2 time.Time
}

type ListLedgerForAnalyticsRow struct {
	Type         string
	OccurredOn   time.Time
	Amount       decimal.Decimal
	Currency     string
	CategoryName pgtype.Text
}

// Spending & cash-flow analytics (Story 8.3 / FR-19). Every income/expense
// transaction in a date window, categorized OR NOT (uncategorized rows still
// count toward cash-flow and group under the empty category name). The money side
// picks the amount + account currency: income credits to_account, expense debits
// from_account. The `type IN ('income','expense')` whitelist scopes this to the
// spending universe: transfers and investment trades (buy/sell/dividend) share
// this same transaction table under other type values (migration 00010, AD-9) and
// are excluded by it — do NOT loosen it. Ordered by date for a stable sequence.
func (q *Queries) ListLedgerForAnalytics(ctx context.Context, arg ListLedgerForAnalyticsParams) ([]ListLedgerForAnalyticsRow, error) {
	rows, err := q.db.Query(ctx, listLedgerForAnalytics, arg.OccurredOn, arg.OccurredOn_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerForAnalyticsRow{}
	for rows.Next() {
		var i ListLedgerForAnalyticsRow
		if err := rows.Scan(
			&i.Type,
			&i.OccurredOn,
			&i.Amount,
			&i.Currency,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
