// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: asset_category.sql

package store

import (
	"context"
)

const createAssetCategory = `-- name: CreateAssetCategory :one
INSERT INTO asset_category (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateAssetCategory(ctx context.Context, name string) (AssetCategory, error) {
	row := q.db.QueryRow(ctx, createAssetCategory, name)
	var i AssetCategory
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteAssetCategory = `-- name: DeleteAssetCategory :execrows
DELETE FROM asset_category WHERE id = $1
`

func (q *Queries) DeleteAssetCategory(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssetCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssetCategory = `-- name: GetAssetCategory :one
SELECT id, name, created_at FROM asset_category WHERE id = $1
`

func (q *Queries) GetAssetCategory(ctx context.Context, id int64) (AssetCategory, error) {
	row := q.db.QueryRow(ctx, getAssetCategory, id)
	var i AssetCategory
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listAssetCategories = `-- name: ListAssetCategories :many
SELECT id, name, created_at FROM asset_category ORDER BY name, id
`

func (q *Queries) ListAssetCategories(ctx context.Context) ([]AssetCategory, error) {
	rows, err := q.db.Query(ctx, listAssetCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetCategory{}
	for rows.Next() {
		var i AssetCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameAssetCategory = `-- name: RenameAssetCategory :execrows
UPDATE asset_category SET name = $2 WHERE id = $1
`

type RenameAssetCategoryParams struct {
	ID   int64
	Name string
}

func (q *Queries) RenameAssetCategory(ctx context.Context, arg RenameAssetCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameAssetCategory, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
