// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: backup.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const exportAccounts = `-- name: ExportAccounts :many

SELECT id, name, type, currency, archived, created_at FROM account ORDER BY id
`

// Full-row export queries for Story 6.1 (authored-data backup). Each SELECT
// lists exactly its table's columns and ORDERs BY id, so sqlc returns the
// existing model structs (store.Account/Category/Security/ExchangeRate/Price/
// Transaction) at full fidelity — primary key, all authored columns, and
// created_at — for a deterministic, byte-stable snapshot that restore (6.2)
// can re-insert parents-before-children.
func (q *Queries) ExportAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, exportAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportBudgets = `-- name: ExportBudgets :many

SELECT id, category_id, amount, created_at FROM budget ORDER BY id
`

// Phase-2 authored tables (Epics 8-10) added to the backup round-trip: budgets,
// auto-categorization rules, recurring templates, and tags + their links. Each
// SELECT lists exactly its table's columns (model-struct order) so sqlc returns
// the existing store models; restore deletes them child→parent and re-inserts
// parent→child with original PKs (identity insert), then resets the sequences.
func (q *Queries) ExportBudgets(ctx context.Context) ([]Budget, error) {
	rows, err := q.db.Query(ctx, exportBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCategories = `-- name: ExportCategories :many
SELECT id, name, kind, created_at FROM category ORDER BY id
`

func (q *Queries) ExportCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, exportCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCategoryRules = `-- name: ExportCategoryRules :many
SELECT id, match_text, category_id, created_at FROM category_rule ORDER BY id
`

func (q *Queries) ExportCategoryRules(ctx context.Context) ([]CategoryRule, error) {
	rows, err := q.db.Query(ctx, exportCategoryRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryRule{}
	for rows.Next() {
		var i CategoryRule
		if err := rows.Scan(
			&i.ID,
			&i.MatchText,
			&i.CategoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportExchangeRates = `-- name: ExportExchangeRates :many
SELECT id, from_currency, to_currency, effective_date, rate, created_at FROM exchange_rate ORDER BY id
`

func (q *Queries) ExportExchangeRates(ctx context.Context) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, exportExchangeRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.ID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.EffectiveDate,
			&i.Rate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportPrices = `-- name: ExportPrices :many
SELECT id, security_id, effective_date, price, created_at FROM price ORDER BY id
`

func (q *Queries) ExportPrices(ctx context.Context) ([]Price, error) {
	rows, err := q.db.Query(ctx, exportPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Price{}
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.SecurityID,
			&i.EffectiveDate,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportRecurring = `-- name: ExportRecurring :many
SELECT id, type, from_account_id, to_account_id, amount, to_amount, category_id,
       cadence, interval_n, start_date, end_date, next_due, description, created_at
FROM recurring ORDER BY id
`

func (q *Queries) ExportRecurring(ctx context.Context) ([]Recurring, error) {
	rows, err := q.db.Query(ctx, exportRecurring)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recurring{}
	for rows.Next() {
		var i Recurring
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.ToAmount,
			&i.CategoryID,
			&i.Cadence,
			&i.IntervalN,
			&i.StartDate,
			&i.EndDate,
			&i.NextDue,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportSecurities = `-- name: ExportSecurities :many
SELECT id, symbol, name, type, quote_currency, created_at FROM security ORDER BY id
`

func (q *Queries) ExportSecurities(ctx context.Context) ([]Security, error) {
	rows, err := q.db.Query(ctx, exportSecurities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Security{}
	for rows.Next() {
		var i Security
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.Type,
			&i.QuoteCurrency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportTags = `-- name: ExportTags :many
SELECT id, name, created_at FROM tag ORDER BY id
`

func (q *Queries) ExportTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, exportTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportTransactionTags = `-- name: ExportTransactionTags :many
SELECT transaction_id, tag_id FROM transaction_tag ORDER BY transaction_id, tag_id
`

func (q *Queries) ExportTransactionTags(ctx context.Context) ([]TransactionTag, error) {
	rows, err := q.db.Query(ctx, exportTransactionTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionTag{}
	for rows.Next() {
		var i TransactionTag
		if err := rows.Scan(&i.TransactionID, &i.TagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportTransactions = `-- name: ExportTransactions :many
SELECT id, type, from_account_id, to_account_id, from_amount, to_amount, occurred_on,
       description, created_at, category_id, import_hash, security_id, quantity, price, fees, fitid, note
FROM transaction ORDER BY id
`

func (q *Queries) ExportTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, exportTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.FromAmount,
			&i.ToAmount,
			&i.OccurredOn,
			&i.Description,
			&i.CreatedAt,
			&i.CategoryID,
			&i.ImportHash,
			&i.SecurityID,
			&i.Quantity,
			&i.Price,
			&i.Fees,
			&i.Fitid,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDeleteAccounts = `-- name: RestoreDeleteAccounts :exec
DELETE FROM account
`

func (q *Queries) RestoreDeleteAccounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDeleteAccounts)
	return err
}

const restoreDeleteBudgets = `-- name: RestoreDeleteBudgets :exec
DELETE FROM budget
`

func (q *Queries) RestoreDeleteBudgets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDeleteBudgets)
	return err
}

const restoreDeleteCategories = `-- name: RestoreDeleteCategories :exec
DELETE FROM category
`

func (q *Queries) RestoreDeleteCategories(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDeleteCategories)
	return err
}

const restoreDeleteCategoryRules = `-- name: RestoreDeleteCategoryRules :exec
DELETE FROM category_rule
`

func (q *Queries) RestoreDeleteCategoryRules(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDeleteCategoryRules)
	return err
}

const restoreDeleteExchangeRates = `-- name: RestoreDeleteExchangeRates :exec
DELETE FROM exchange_rate
`

func (q *Queries) RestoreDeleteExchangeRates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDeleteExchangeRates)
	return err
}

const restoreDeletePrices = `-- name: RestoreDeletePrices :exec
DELETE FROM price
`

func (q *Queries) RestoreDeletePrices(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDeletePrices)
	return err
}

const restoreDeleteRecurring = `-- name: RestoreDeleteRecurring :exec
DELETE FROM recurring
`

func (q *Queries) RestoreDeleteRecurring(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDeleteRecurring)
	return err
}

const restoreDeleteSecurities = `-- name: RestoreDeleteSecurities :exec
DELETE FROM security
`

func (q *Queries) RestoreDeleteSecurities(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDeleteSecurities)
	return err
}

const restoreDeleteTags = `-- name: RestoreDeleteTags :exec
DELETE FROM tag
`

func (q *Queries) RestoreDeleteTags(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDeleteTags)
	return err
}

const restoreDeleteTransactionTags = `-- name: RestoreDeleteTransactionTags :exec
DELETE FROM transaction_tag
`

func (q *Queries) RestoreDeleteTransactionTags(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDeleteTransactionTags)
	return err
}

const restoreDeleteTransactions = `-- name: RestoreDeleteTransactions :exec

DELETE FROM transaction
`

// Restore queries for Story 6.2 (recover from a 6.1 export). Restore is a
// replace-all operation inside one transaction (AD-3): delete every authored row
// child→parent, re-insert each row parent→child with its ORIGINAL primary key
// and created_at (OVERRIDING SYSTEM VALUE — the PKs are GENERATED ALWAYS AS
// IDENTITY), then reset each identity sequence past the restored ids. Derived
// figures are never written; they recompute on read (AD-2).
func (q *Queries) RestoreDeleteTransactions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDeleteTransactions)
	return err
}

const restoreInsertAccount = `-- name: RestoreInsertAccount :exec
INSERT INTO account (id, name, type, currency, archived, created_at)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4, $5, $6)
`

type RestoreInsertAccountParams struct {
	ID        int64
	Name      string
	Type      string
	Currency  string
	Archived  bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) RestoreInsertAccount(ctx context.Context, arg RestoreInsertAccountParams) error {
	_, err := q.db.Exec(ctx, restoreInsertAccount,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Archived,
		arg.CreatedAt,
	)
	return err
}

const restoreInsertBudget = `-- name: RestoreInsertBudget :exec
INSERT INTO budget (id, category_id, amount, created_at)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4)
`

type RestoreInsertBudgetParams struct {
	ID         int64
	CategoryID int64
	Amount     decimal.Decimal
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) RestoreInsertBudget(ctx context.Context, arg RestoreInsertBudgetParams) error {
	_, err := q.db.Exec(ctx, restoreInsertBudget,
		arg.ID,
		arg.CategoryID,
		arg.Amount,
		arg.CreatedAt,
	)
	return err
}

const restoreInsertCategory = `-- name: RestoreInsertCategory :exec
INSERT INTO category (id, name, kind, created_at)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4)
`

type RestoreInsertCategoryParams struct {
	ID        int64
	Name      string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) RestoreInsertCategory(ctx context.Context, arg RestoreInsertCategoryParams) error {
	_, err := q.db.Exec(ctx, restoreInsertCategory,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.CreatedAt,
	)
	return err
}

const restoreInsertCategoryRule = `-- name: RestoreInsertCategoryRule :exec
INSERT INTO category_rule (id, match_text, category_id, created_at)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4)
`

type RestoreInsertCategoryRuleParams struct {
	ID         int64
	MatchText  string
	CategoryID int64
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) RestoreInsertCategoryRule(ctx context.Context, arg RestoreInsertCategoryRuleParams) error {
	_, err := q.db.Exec(ctx, restoreInsertCategoryRule,
		arg.ID,
		arg.MatchText,
		arg.CategoryID,
		arg.CreatedAt,
	)
	return err
}

const restoreInsertExchangeRate = `-- name: RestoreInsertExchangeRate :exec
INSERT INTO exchange_rate (id, from_currency, to_currency, effective_date, rate, created_at)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4, $5, $6)
`

type RestoreInsertExchangeRateParams struct {
	ID            int64
	FromCurrency  string
	ToCurrency    string
	EffectiveDate time.Time
	Rate          decimal.Decimal
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) RestoreInsertExchangeRate(ctx context.Context, arg RestoreInsertExchangeRateParams) error {
	_, err := q.db.Exec(ctx, restoreInsertExchangeRate,
		arg.ID,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.EffectiveDate,
		arg.Rate,
		arg.CreatedAt,
	)
	return err
}

const restoreInsertPrice = `-- name: RestoreInsertPrice :exec
INSERT INTO price (id, security_id, effective_date, price, created_at)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4, $5)
`

type RestoreInsertPriceParams struct {
	ID            int64
	SecurityID    int64
	EffectiveDate time.Time
	Price         decimal.Decimal
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) RestoreInsertPrice(ctx context.Context, arg RestoreInsertPriceParams) error {
	_, err := q.db.Exec(ctx, restoreInsertPrice,
		arg.ID,
		arg.SecurityID,
		arg.EffectiveDate,
		arg.Price,
		arg.CreatedAt,
	)
	return err
}

const restoreInsertRecurring = `-- name: RestoreInsertRecurring :exec
INSERT INTO recurring (id, type, from_account_id, to_account_id, amount, to_amount, category_id,
                       cadence, interval_n, start_date, end_date, next_due, description, created_at)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type RestoreInsertRecurringParams struct {
	ID            int64
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	Amount        decimal.Decimal
	ToAmount      decimal.Decimal
	CategoryID    pgtype.Int8
	Cadence       string
	IntervalN     int32
	StartDate     time.Time
	EndDate       pgtype.Date
	NextDue       time.Time
	Description   string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) RestoreInsertRecurring(ctx context.Context, arg RestoreInsertRecurringParams) error {
	_, err := q.db.Exec(ctx, restoreInsertRecurring,
		arg.ID,
		arg.Type,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.ToAmount,
		arg.CategoryID,
		arg.Cadence,
		arg.IntervalN,
		arg.StartDate,
		arg.EndDate,
		arg.NextDue,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}

const restoreInsertSecurity = `-- name: RestoreInsertSecurity :exec
INSERT INTO security (id, symbol, name, type, quote_currency, created_at)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4, $5, $6)
`

type RestoreInsertSecurityParams struct {
	ID            int64
	Symbol        string
	Name          string
	Type          string
	QuoteCurrency string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) RestoreInsertSecurity(ctx context.Context, arg RestoreInsertSecurityParams) error {
	_, err := q.db.Exec(ctx, restoreInsertSecurity,
		arg.ID,
		arg.Symbol,
		arg.Name,
		arg.Type,
		arg.QuoteCurrency,
		arg.CreatedAt,
	)
	return err
}

const restoreInsertTag = `-- name: RestoreInsertTag :exec
INSERT INTO tag (id, name, created_at)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3)
`

type RestoreInsertTagParams struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) RestoreInsertTag(ctx context.Context, arg RestoreInsertTagParams) error {
	_, err := q.db.Exec(ctx, restoreInsertTag, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const restoreInsertTransaction = `-- name: RestoreInsertTransaction :exec
INSERT INTO transaction (id, type, from_account_id, to_account_id, from_amount, to_amount,
                         occurred_on, description, created_at, category_id, import_hash,
                         security_id, quantity, price, fees, fitid, note)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
`

type RestoreInsertTransactionParams struct {
	ID            int64
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	FromAmount    decimal.Decimal
	ToAmount      decimal.Decimal
	OccurredOn    time.Time
	Description   string
	CreatedAt     pgtype.Timestamptz
	CategoryID    pgtype.Int8
	ImportHash    pgtype.Text
	SecurityID    pgtype.Int8
	Quantity      decimal.Decimal
	Price         decimal.Decimal
	Fees          decimal.Decimal
	Fitid         pgtype.Text
	Note          string
}

func (q *Queries) RestoreInsertTransaction(ctx context.Context, arg RestoreInsertTransactionParams) error {
	_, err := q.db.Exec(ctx, restoreInsertTransaction,
		arg.ID,
		arg.Type,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.FromAmount,
		arg.ToAmount,
		arg.OccurredOn,
		arg.Description,
		arg.CreatedAt,
		arg.CategoryID,
		arg.ImportHash,
		arg.SecurityID,
		arg.Quantity,
		arg.Price,
		arg.Fees,
		arg.Fitid,
		arg.Note,
	)
	return err
}

const restoreInsertTransactionTag = `-- name: RestoreInsertTransactionTag :exec
INSERT INTO transaction_tag (transaction_id, tag_id)
VALUES ($1, $2)
`

type RestoreInsertTransactionTagParams struct {
	TransactionID int64
	TagID         int64
}

func (q *Queries) RestoreInsertTransactionTag(ctx context.Context, arg RestoreInsertTransactionTagParams) error {
	_, err := q.db.Exec(ctx, restoreInsertTransactionTag, arg.TransactionID, arg.TagID)
	return err
}

const restoreResetAccountSeq = `-- name: RestoreResetAccountSeq :exec
SELECT setval(pg_get_serial_sequence('account', 'id'),
              COALESCE((SELECT MAX(id) FROM account), 1),
              (SELECT MAX(id) FROM account) IS NOT NULL)
`

func (q *Queries) RestoreResetAccountSeq(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreResetAccountSeq)
	return err
}

const restoreResetBudgetSeq = `-- name: RestoreResetBudgetSeq :exec
SELECT setval(pg_get_serial_sequence('budget', 'id'),
              COALESCE((SELECT MAX(id) FROM budget), 1),
              (SELECT MAX(id) FROM budget) IS NOT NULL)
`

func (q *Queries) RestoreResetBudgetSeq(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreResetBudgetSeq)
	return err
}

const restoreResetCategoryRuleSeq = `-- name: RestoreResetCategoryRuleSeq :exec
SELECT setval(pg_get_serial_sequence('category_rule', 'id'),
              COALESCE((SELECT MAX(id) FROM category_rule), 1),
              (SELECT MAX(id) FROM category_rule) IS NOT NULL)
`

func (q *Queries) RestoreResetCategoryRuleSeq(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreResetCategoryRuleSeq)
	return err
}

const restoreResetCategorySeq = `-- name: RestoreResetCategorySeq :exec
SELECT setval(pg_get_serial_sequence('category', 'id'),
              COALESCE((SELECT MAX(id) FROM category), 1),
              (SELECT MAX(id) FROM category) IS NOT NULL)
`

func (q *Queries) RestoreResetCategorySeq(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreResetCategorySeq)
	return err
}

const restoreResetExchangeRateSeq = `-- name: RestoreResetExchangeRateSeq :exec
SELECT setval(pg_get_serial_sequence('exchange_rate', 'id'),
              COALESCE((SELECT MAX(id) FROM exchange_rate), 1),
              (SELECT MAX(id) FROM exchange_rate) IS NOT NULL)
`

func (q *Queries) RestoreResetExchangeRateSeq(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreResetExchangeRateSeq)
	return err
}

const restoreResetPriceSeq = `-- name: RestoreResetPriceSeq :exec
SELECT setval(pg_get_serial_sequence('price', 'id'),
              COALESCE((SELECT MAX(id) FROM price), 1),
              (SELECT MAX(id) FROM price) IS NOT NULL)
`

func (q *Queries) RestoreResetPriceSeq(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreResetPriceSeq)
	return err
}

const restoreResetRecurringSeq = `-- name: RestoreResetRecurringSeq :exec
SELECT setval(pg_get_serial_sequence('recurring', 'id'),
              COALESCE((SELECT MAX(id) FROM recurring), 1),
              (SELECT MAX(id) FROM recurring) IS NOT NULL)
`

func (q *Queries) RestoreResetRecurringSeq(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreResetRecurringSeq)
	return err
}

const restoreResetSecuritySeq = `-- name: RestoreResetSecuritySeq :exec
SELECT setval(pg_get_serial_sequence('security', 'id'),
              COALESCE((SELECT MAX(id) FROM security), 1),
              (SELECT MAX(id) FROM security) IS NOT NULL)
`

func (q *Queries) RestoreResetSecuritySeq(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreResetSecuritySeq)
	return err
}

const restoreResetTagSeq = `-- name: RestoreResetTagSeq :exec
SELECT setval(pg_get_serial_sequence('tag', 'id'),
              COALESCE((SELECT MAX(id) FROM tag), 1),
              (SELECT MAX(id) FROM tag) IS NOT NULL)
`

func (q *Queries) RestoreResetTagSeq(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreResetTagSeq)
	return err
}

const restoreResetTransactionSeq = `-- name: RestoreResetTransactionSeq :exec
SELECT setval(pg_get_serial_sequence('transaction', 'id'),
              COALESCE((SELECT MAX(id) FROM transaction), 1),
              (SELECT MAX(id) FROM transaction) IS NOT NULL)
`

func (q *Queries) RestoreResetTransactionSeq(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreResetTransactionSeq)
	return err
}
