// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: backup.sql

package store

import (
	"context"
)

const exportAccounts = `-- name: ExportAccounts :many

SELECT id, name, type, currency, archived, created_at FROM account ORDER BY id
`

// Full-row export queries for Story 6.1 (authored-data backup). Each SELECT
// lists exactly its table's columns and ORDERs BY id, so sqlc returns the
// existing model structs (store.Account/Category/Security/ExchangeRate/Price/
// Transaction) at full fidelity — primary key, all authored columns, and
// created_at — for a deterministic, byte-stable snapshot that restore (6.2)
// can re-insert parents-before-children.
func (q *Queries) ExportAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, exportAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCategories = `-- name: ExportCategories :many
SELECT id, name, kind, created_at FROM category ORDER BY id
`

func (q *Queries) ExportCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, exportCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportExchangeRates = `-- name: ExportExchangeRates :many
SELECT id, from_currency, to_currency, effective_date, rate, created_at FROM exchange_rate ORDER BY id
`

func (q *Queries) ExportExchangeRates(ctx context.Context) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, exportExchangeRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.ID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.EffectiveDate,
			&i.Rate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportPrices = `-- name: ExportPrices :many
SELECT id, security_id, effective_date, price, created_at FROM price ORDER BY id
`

func (q *Queries) ExportPrices(ctx context.Context) ([]Price, error) {
	rows, err := q.db.Query(ctx, exportPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Price{}
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.SecurityID,
			&i.EffectiveDate,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportSecurities = `-- name: ExportSecurities :many
SELECT id, symbol, name, type, quote_currency, created_at FROM security ORDER BY id
`

func (q *Queries) ExportSecurities(ctx context.Context) ([]Security, error) {
	rows, err := q.db.Query(ctx, exportSecurities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Security{}
	for rows.Next() {
		var i Security
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.Type,
			&i.QuoteCurrency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportTransactions = `-- name: ExportTransactions :many
SELECT id, type, from_account_id, to_account_id, from_amount, to_amount, occurred_on,
       description, created_at, category_id, import_hash, security_id, quantity, price, fees
FROM transaction ORDER BY id
`

func (q *Queries) ExportTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, exportTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.FromAmount,
			&i.ToAmount,
			&i.OccurredOn,
			&i.Description,
			&i.CreatedAt,
			&i.CategoryID,
			&i.ImportHash,
			&i.SecurityID,
			&i.Quantity,
			&i.Price,
			&i.Fees,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
