// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: budget.sql

package store

import (
	"context"

	"github.com/shopspring/decimal"
)

const deleteBudget = `-- name: DeleteBudget :execrows
DELETE FROM budget WHERE category_id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, categoryID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBudget, categoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBudgets = `-- name: ListBudgets :many
SELECT b.id, b.category_id, b.amount, c.name AS category_name, c.kind AS category_kind
FROM budget b
JOIN category c ON c.id = b.category_id
ORDER BY c.kind, c.name, c.id
`

type ListBudgetsRow struct {
	ID           int64
	CategoryID   int64
	Amount       decimal.Decimal
	CategoryName string
	CategoryKind string
}

func (q *Queries) ListBudgets(ctx context.Context) ([]ListBudgetsRow, error) {
	rows, err := q.db.Query(ctx, listBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsRow{}
	for rows.Next() {
		var i ListBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Amount,
			&i.CategoryName,
			&i.CategoryKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBudget = `-- name: SetBudget :one

INSERT INTO budget (category_id, amount)
VALUES ($1, $2)
ON CONFLICT (category_id) DO UPDATE SET amount = EXCLUDED.amount
RETURNING id, category_id, amount, created_at
`

type SetBudgetParams struct {
	CategoryID int64
	Amount     decimal.Decimal
}

// Monthly category budgets (Story 8.1 / FR-18). One target per category, keyed by
// category_id (UNIQUE), so SetBudget upserts. ListBudgets joins category to return
// its name + kind for the management view, ordered by kind then name (stable with
// the categories list).
func (q *Queries) SetBudget(ctx context.Context, arg SetBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, setBudget, arg.CategoryID, arg.Amount)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
