// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: category_rule.sql

package store

import (
	"context"
)

const createCategoryRule = `-- name: CreateCategoryRule :one

INSERT INTO category_rule (match_text, category_id)
VALUES ($1, $2)
RETURNING id, match_text, category_id, created_at
`

type CreateCategoryRuleParams struct {
	MatchText  string
	CategoryID int64
}

// Auto-categorization rules (Story 7.2 / FR-17). A rule inherits its category's
// kind, so ListCategoryRules joins category to return kind + name for the matcher
// and the management UI, ordered by id (insertion order ⇒ first-match-wins).
func (q *Queries) CreateCategoryRule(ctx context.Context, arg CreateCategoryRuleParams) (CategoryRule, error) {
	row := q.db.QueryRow(ctx, createCategoryRule, arg.MatchText, arg.CategoryID)
	var i CategoryRule
	err := row.Scan(
		&i.ID,
		&i.MatchText,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategoryRule = `-- name: DeleteCategoryRule :execrows
DELETE FROM category_rule WHERE id = $1
`

func (q *Queries) DeleteCategoryRule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategoryRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCategoryRules = `-- name: ListCategoryRules :many
SELECT r.id, r.match_text, r.category_id, c.name AS category_name, c.kind AS category_kind
FROM category_rule r
JOIN category c ON c.id = r.category_id
ORDER BY r.id
`

type ListCategoryRulesRow struct {
	ID           int64
	MatchText    string
	CategoryID   int64
	CategoryName string
	CategoryKind string
}

func (q *Queries) ListCategoryRules(ctx context.Context) ([]ListCategoryRulesRow, error) {
	rows, err := q.db.Query(ctx, listCategoryRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoryRulesRow{}
	for rows.Next() {
		var i ListCategoryRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchText,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
