// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: category.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryUsageCounts = `-- name: CategoryUsageCounts :many
SELECT category_id, COUNT(*) AS n
FROM transaction
WHERE category_id IS NOT NULL
GROUP BY category_id
`

type CategoryUsageCountsRow struct {
	CategoryID pgtype.Int8
	N          int64
}

func (q *Queries) CategoryUsageCounts(ctx context.Context) ([]CategoryUsageCountsRow, error) {
	rows, err := q.db.Query(ctx, categoryUsageCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryUsageCountsRow{}
	for rows.Next() {
		var i CategoryUsageCountsRow
		if err := rows.Scan(&i.CategoryID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearCategoryFromTransactions = `-- name: ClearCategoryFromTransactions :execrows
UPDATE transaction SET category_id = NULL WHERE category_id = $1
`

func (q *Queries) ClearCategoryFromTransactions(ctx context.Context, categoryID pgtype.Int8) (int64, error) {
	result, err := q.db.Exec(ctx, clearCategoryFromTransactions, categoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO category (name, kind)
VALUES ($1, $2)
RETURNING id, name, kind, created_at
`

type CreateCategoryParams struct {
	Name string
	Kind string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Kind)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM category WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, kind, created_at FROM category WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, kind, created_at FROM category ORDER BY kind, name, id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryTransactions = `-- name: ListCategoryTransactions :many
SELECT id, type, from_account_id, to_account_id, from_amount, to_amount, occurred_on, description, created_at, category_id, import_hash, security_id, quantity, price, fees, fitid
FROM transaction
WHERE category_id = $1
ORDER BY occurred_on DESC, id DESC
`

func (q *Queries) ListCategoryTransactions(ctx context.Context, categoryID pgtype.Int8) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listCategoryTransactions, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.FromAmount,
			&i.ToAmount,
			&i.OccurredOn,
			&i.Description,
			&i.CreatedAt,
			&i.CategoryID,
			&i.ImportHash,
			&i.SecurityID,
			&i.Quantity,
			&i.Price,
			&i.Fees,
			&i.Fitid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
