// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exchange_rate.sql

package store

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const addExchangeRate = `-- name: AddExchangeRate :one
INSERT INTO exchange_rate (from_currency, to_currency, effective_date, rate)
VALUES ($1, $2, $3, $4)
RETURNING id, from_currency, to_currency, effective_date, rate, created_at
`

type AddExchangeRateParams struct {
	FromCurrency  string
	ToCurrency    string
	EffectiveDate time.Time
	Rate          decimal.Decimal
}

func (q *Queries) AddExchangeRate(ctx context.Context, arg AddExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, addExchangeRate,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.EffectiveDate,
		arg.Rate,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.EffectiveDate,
		&i.Rate,
		&i.CreatedAt,
	)
	return i, err
}

const listExchangeRates = `-- name: ListExchangeRates :many
SELECT id, from_currency, to_currency, effective_date, rate, created_at
FROM exchange_rate
ORDER BY effective_date DESC, id DESC
`

func (q *Queries) ListExchangeRates(ctx context.Context) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, listExchangeRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.ID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.EffectiveDate,
			&i.Rate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rateEffectiveAt = `-- name: RateEffectiveAt :one
SELECT rate FROM exchange_rate
WHERE from_currency = $1 AND to_currency = $2 AND effective_date <= $3
ORDER BY effective_date DESC, id DESC
LIMIT 1
`

type RateEffectiveAtParams struct {
	FromCurrency  string
	ToCurrency    string
	EffectiveDate time.Time
}

func (q *Queries) RateEffectiveAt(ctx context.Context, arg RateEffectiveAtParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, rateEffectiveAt, arg.FromCurrency, arg.ToCurrency, arg.EffectiveDate)
	var rate decimal.Decimal
	err := row.Scan(&rate)
	return rate, err
}
