// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID        int64
	Name      string
	Type      string
	Currency  string
	Archived  bool
	CreatedAt pgtype.Timestamptz
}

type AppSetting struct {
	ID              bool
	DisplayCurrency string
}

type AssetCategory struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Budget struct {
	ID         int64
	CategoryID int64
	Amount     decimal.Decimal
	CreatedAt  pgtype.Timestamptz
}

type Category struct {
	ID        int64
	Name      string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

type CategoryRule struct {
	ID         int64
	MatchText  string
	CategoryID int64
	CreatedAt  pgtype.Timestamptz
}

type Currency struct {
	Code string
	Name string
}

type ExchangeRate struct {
	ID            int64
	FromCurrency  string
	ToCurrency    string
	EffectiveDate time.Time
	Rate          decimal.Decimal
	CreatedAt     pgtype.Timestamptz
}

type Price struct {
	ID            int64
	SecurityID    int64
	EffectiveDate time.Time
	Price         decimal.Decimal
	CreatedAt     pgtype.Timestamptz
}

type Recurring struct {
	ID            int64
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	Amount        decimal.Decimal
	ToAmount      decimal.Decimal
	CategoryID    pgtype.Int8
	Cadence       string
	IntervalN     int32
	StartDate     time.Time
	EndDate       pgtype.Date
	NextDue       time.Time
	Description   string
	CreatedAt     pgtype.Timestamptz
}

type Security struct {
	ID            int64
	Symbol        string
	Name          string
	Type          string
	QuoteCurrency string
	CreatedAt     pgtype.Timestamptz
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Transaction struct {
	ID            int64
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	FromAmount    decimal.Decimal
	ToAmount      decimal.Decimal
	OccurredOn    time.Time
	Description   string
	CreatedAt     pgtype.Timestamptz
	CategoryID    pgtype.Int8
	ImportHash    pgtype.Text
	SecurityID    pgtype.Int8
	Quantity      decimal.Decimal
	Price         decimal.Decimal
	Fees          decimal.Decimal
	Fitid         pgtype.Text
	Note          string
}

type TransactionTag struct {
	TransactionID int64
	TagID         int64
}
