// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID        int64
	Name      string
	Type      string
	Currency  string
	Archived  bool
	CreatedAt pgtype.Timestamptz
}

type AppSetting struct {
	ID              bool
	DisplayCurrency string
}

type Currency struct {
	Code string
	Name string
}

type ExchangeRate struct {
	ID            int64
	FromCurrency  string
	ToCurrency    string
	EffectiveDate time.Time
	Rate          decimal.Decimal
	CreatedAt     pgtype.Timestamptz
}
