// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: price.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const addPrice = `-- name: AddPrice :one
INSERT INTO price (security_id, effective_date, price)
VALUES ($1, $2, $3)
RETURNING id, security_id, effective_date, price, created_at
`

type AddPriceParams struct {
	SecurityID    int64
	EffectiveDate time.Time
	Price         decimal.Decimal
}

func (q *Queries) AddPrice(ctx context.Context, arg AddPriceParams) (Price, error) {
	row := q.db.QueryRow(ctx, addPrice, arg.SecurityID, arg.EffectiveDate, arg.Price)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.SecurityID,
		&i.EffectiveDate,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const latestPrices = `-- name: LatestPrices :many
SELECT DISTINCT ON (security_id) security_id, effective_date, price
FROM price
WHERE effective_date <= $1
ORDER BY security_id, effective_date DESC, id DESC
`

type LatestPricesRow struct {
	SecurityID    int64
	EffectiveDate time.Time
	Price         decimal.Decimal
}

func (q *Queries) LatestPrices(ctx context.Context, effectiveDate time.Time) ([]LatestPricesRow, error) {
	rows, err := q.db.Query(ctx, latestPrices, effectiveDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestPricesRow{}
	for rows.Next() {
		var i LatestPricesRow
		if err := rows.Scan(&i.SecurityID, &i.EffectiveDate, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrices = `-- name: ListPrices :many
SELECT p.id, p.security_id, s.symbol, p.effective_date, p.price, p.created_at
FROM price p
JOIN security s ON s.id = p.security_id
ORDER BY p.effective_date DESC, p.id DESC
`

type ListPricesRow struct {
	ID            int64
	SecurityID    int64
	Symbol        string
	EffectiveDate time.Time
	Price         decimal.Decimal
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListPrices(ctx context.Context) ([]ListPricesRow, error) {
	rows, err := q.db.Query(ctx, listPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPricesRow{}
	for rows.Next() {
		var i ListPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.SecurityID,
			&i.Symbol,
			&i.EffectiveDate,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const priceEffectiveAt = `-- name: PriceEffectiveAt :one
SELECT price FROM price
WHERE security_id = $1 AND effective_date <= $2
ORDER BY effective_date DESC, id DESC
LIMIT 1
`

type PriceEffectiveAtParams struct {
	SecurityID    int64
	EffectiveDate time.Time
}

func (q *Queries) PriceEffectiveAt(ctx context.Context, arg PriceEffectiveAtParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, priceEffectiveAt, arg.SecurityID, arg.EffectiveDate)
	var price decimal.Decimal
	err := row.Scan(&price)
	return price, err
}
