// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Querier interface {
	AddExchangeRate(ctx context.Context, arg AddExchangeRateParams) (ExchangeRate, error)
	AddPrice(ctx context.Context, arg AddPriceParams) (Price, error)
	// Assign one category to many transactions in a single statement (Story 10.1,
	// one tx AD-3). The type guard scopes the write to rows matching the category's
	// kind, so a transfer/trade id can never be categorized even if submitted.
	BulkSetCategory(ctx context.Context, arg BulkSetCategoryParams) (int64, error)
	CategoryUsageCounts(ctx context.Context) ([]CategoryUsageCountsRow, error)
	ClearCategoryFromTransactions(ctx context.Context, categoryID pgtype.Int8) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	// Auto-categorization rules (Story 7.2 / FR-17). A rule inherits its category's
	// kind, so ListCategoryRules joins category to return kind + name for the matcher
	// and the management UI, ordered by id (insertion order ⇒ first-match-wins).
	CreateCategoryRule(ctx context.Context, arg CreateCategoryRuleParams) (CategoryRule, error)
	CreateImportedTransaction(ctx context.Context, arg CreateImportedTransactionParams) (int64, error)
	// OFX import (FR-16): an Income/Expense row carrying the bank's FITID (or NULL
	// when the STMTTRN has none). category_id and import_hash default NULL — OFX
	// dedup is FITID-only, never the tab importer's content hash.
	CreateOFXTransaction(ctx context.Context, arg CreateOFXTransactionParams) (int64, error)
	// Recurring transaction templates (Epic 9 / FR-20). One-row ledger convention:
	// income credits to_account_id, expense debits from_account_id, a transfer
	// populates both; to_amount is the cross-currency destination leg (0 otherwise).
	// next_due is the authored schedule cursor advanced on post/skip (UpdateRecurringNextDue).
	// GetRecurringForUpdate row-locks the template so a post/skip serializes against a
	// concurrent one (idempotent one-click posting — no double-post of an occurrence).
	CreateRecurring(ctx context.Context, arg CreateRecurringParams) (Recurring, error)
	CreateSecurity(ctx context.Context, arg CreateSecurityParams) (Security, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteBudget(ctx context.Context, categoryID int64) (int64, error)
	DeleteCategory(ctx context.Context, id int64) (int64, error)
	DeleteCategoryRule(ctx context.Context, id int64) (int64, error)
	DeleteRecurring(ctx context.Context, id int64) (int64, error)
	DeleteTransaction(ctx context.Context, id int64) (int64, error)
	// Full-row export queries for Story 6.1 (authored-data backup). Each SELECT
	// lists exactly its table's columns and ORDERs BY id, so sqlc returns the
	// existing model structs (store.Account/Category/Security/ExchangeRate/Price/
	// Transaction) at full fidelity — primary key, all authored columns, and
	// created_at — for a deterministic, byte-stable snapshot that restore (6.2)
	// can re-insert parents-before-children.
	ExportAccounts(ctx context.Context) ([]Account, error)
	ExportCategories(ctx context.Context) ([]Category, error)
	ExportExchangeRates(ctx context.Context) ([]ExchangeRate, error)
	ExportPrices(ctx context.Context) ([]Price, error)
	ExportSecurities(ctx context.Context) ([]Security, error)
	ExportTransactions(ctx context.Context) ([]Transaction, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetDisplayCurrency(ctx context.Context) (string, error)
	GetRecurring(ctx context.Context, id int64) (Recurring, error)
	GetRecurringForUpdate(ctx context.Context, id int64) (Recurring, error)
	GetSecurity(ctx context.Context, id int64) (Security, error)
	GetSecurityBySymbol(ctx context.Context, symbol string) (Security, error)
	// $1 is cast to a calendar DATE so "effective on or before today" is a stable
	// date-to-date comparison (no sub-day/timezone boundary flapping when an instant
	// is passed).
	LatestPrices(ctx context.Context, dollar_1 time.Time) ([]LatestPricesRow, error)
	ListAccountFitids(ctx context.Context, fromAccountID pgtype.Int8) ([]pgtype.Text, error)
	ListAccountImportHashes(ctx context.Context, fromAccountID pgtype.Int8) ([]pgtype.Text, error)
	ListAccountTransactions(ctx context.Context, fromAccountID pgtype.Int8) ([]Transaction, error)
	ListActiveAccounts(ctx context.Context) ([]Account, error)
	ListAllAccounts(ctx context.Context) ([]Account, error)
	ListBudgets(ctx context.Context) ([]ListBudgetsRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	// Categorized income/expense transactions with occurred_on before an exclusive
	// upper bound (the first day of the month after the selected one), for the budget
	// view's actuals + carryover chain (Story 8.2 / FR-18). The native magnitude and
	// currency come from the money side of the row: income credits to_account,
	// expense debits from_account. The `type IN ('income','expense')` whitelist is the
	// guard that scopes this to budget spending: transfers and investment trades
	// (buy/sell/dividend) share this same transaction table under other type values
	// (migration 00010, AD-9), and the whitelist excludes them — do NOT loosen it to
	// `type != 'transfer'` or trades would leak into actuals. Ordered by date so the
	// domain sees a stable sequence.
	ListCategorizedForBudget(ctx context.Context, occurredOn time.Time) ([]ListCategorizedForBudgetRow, error)
	ListCategoryRules(ctx context.Context) ([]ListCategoryRulesRow, error)
	ListCategoryTransactions(ctx context.Context, categoryID pgtype.Int8) ([]Transaction, error)
	ListCurrencies(ctx context.Context) ([]Currency, error)
	ListExchangeRates(ctx context.Context) ([]ExchangeRate, error)
	// Spending & cash-flow analytics (Story 8.3 / FR-19). Every income/expense
	// transaction in a date window, categorized OR NOT (uncategorized rows still
	// count toward cash-flow and group under the empty category name). The money side
	// picks the amount + account currency: income credits to_account, expense debits
	// from_account. The `type IN ('income','expense')` whitelist scopes this to the
	// spending universe: transfers and investment trades (buy/sell/dividend) share
	// this same transaction table under other type values (migration 00010, AD-9) and
	// are excluded by it — do NOT loosen it. Ordered by date for a stable sequence.
	ListLedgerForAnalytics(ctx context.Context, arg ListLedgerForAnalyticsParams) ([]ListLedgerForAnalyticsRow, error)
	ListPrices(ctx context.Context) ([]ListPricesRow, error)
	// Every template with its account and category names joined for display, ordered
	// by next_due then id so the soonest-due surface first.
	ListRecurring(ctx context.Context) ([]ListRecurringRow, error)
	ListSecurities(ctx context.Context) ([]Security, error)
	// The (id, type) of the given transactions, for validating a bulk-categorize
	// selection (Story 10.1): every selected row must exist and be income/expense of
	// the category's kind. Transfers/trades are returned with their type so the
	// service can reject them (they are not categorizable, AD-9).
	ListTransactionKindsByIDs(ctx context.Context, dollar_1 []int64) ([]ListTransactionKindsByIDsRow, error)
	ListTransactions(ctx context.Context) ([]Transaction, error)
	PriceEffectiveAt(ctx context.Context, arg PriceEffectiveAtParams) (decimal.Decimal, error)
	RateEffectiveAt(ctx context.Context, arg RateEffectiveAtParams) (decimal.Decimal, error)
	RenameAccount(ctx context.Context, arg RenameAccountParams) (int64, error)
	RestoreDeleteAccounts(ctx context.Context) error
	RestoreDeleteCategories(ctx context.Context) error
	RestoreDeleteExchangeRates(ctx context.Context) error
	RestoreDeletePrices(ctx context.Context) error
	RestoreDeleteSecurities(ctx context.Context) error
	// Restore queries for Story 6.2 (recover from a 6.1 export). Restore is a
	// replace-all operation inside one transaction (AD-3): delete every authored row
	// child→parent, re-insert each row parent→child with its ORIGINAL primary key
	// and created_at (OVERRIDING SYSTEM VALUE — the PKs are GENERATED ALWAYS AS
	// IDENTITY), then reset each identity sequence past the restored ids. Derived
	// figures are never written; they recompute on read (AD-2).
	RestoreDeleteTransactions(ctx context.Context) error
	RestoreInsertAccount(ctx context.Context, arg RestoreInsertAccountParams) error
	RestoreInsertCategory(ctx context.Context, arg RestoreInsertCategoryParams) error
	RestoreInsertExchangeRate(ctx context.Context, arg RestoreInsertExchangeRateParams) error
	RestoreInsertPrice(ctx context.Context, arg RestoreInsertPriceParams) error
	RestoreInsertSecurity(ctx context.Context, arg RestoreInsertSecurityParams) error
	RestoreInsertTransaction(ctx context.Context, arg RestoreInsertTransactionParams) error
	RestoreResetAccountSeq(ctx context.Context) error
	RestoreResetCategorySeq(ctx context.Context) error
	RestoreResetExchangeRateSeq(ctx context.Context) error
	RestoreResetPriceSeq(ctx context.Context) error
	RestoreResetSecuritySeq(ctx context.Context) error
	RestoreResetTransactionSeq(ctx context.Context) error
	SetAccountArchived(ctx context.Context, arg SetAccountArchivedParams) (int64, error)
	// Monthly category budgets (Story 8.1 / FR-18). One target per category, keyed by
	// category_id (UNIQUE), so SetBudget upserts. ListBudgets joins category to return
	// its name + kind for the management view, ordered by kind then name (stable with
	// the categories list).
	SetBudget(ctx context.Context, arg SetBudgetParams) (Budget, error)
	SetDisplayCurrency(ctx context.Context, displayCurrency string) error
	UpdateRecurring(ctx context.Context, arg UpdateRecurringParams) (int64, error)
	UpdateRecurringNextDue(ctx context.Context, arg UpdateRecurringNextDueParams) (int64, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
