// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: recurring.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createRecurring = `-- name: CreateRecurring :one

INSERT INTO recurring (
    type, from_account_id, to_account_id, amount, to_amount,
    category_id, cadence, interval_n, start_date, end_date, next_due, description
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, type, from_account_id, to_account_id, amount, to_amount,
    category_id, cadence, interval_n, start_date, end_date, next_due, description, created_at
`

type CreateRecurringParams struct {
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	Amount        decimal.Decimal
	ToAmount      decimal.Decimal
	CategoryID    pgtype.Int8
	Cadence       string
	IntervalN     int32
	StartDate     time.Time
	EndDate       pgtype.Date
	NextDue       time.Time
	Description   string
}

// Recurring transaction templates (Epic 9 / FR-20). One-row ledger convention:
// income credits to_account_id, expense debits from_account_id, a transfer
// populates both; to_amount is the cross-currency destination leg (0 otherwise).
// next_due is the authored schedule cursor advanced on post/skip (UpdateRecurringNextDue).
// GetRecurringForUpdate row-locks the template so a post/skip serializes against a
// concurrent one (idempotent one-click posting — no double-post of an occurrence).
func (q *Queries) CreateRecurring(ctx context.Context, arg CreateRecurringParams) (Recurring, error) {
	row := q.db.QueryRow(ctx, createRecurring,
		arg.Type,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.ToAmount,
		arg.CategoryID,
		arg.Cadence,
		arg.IntervalN,
		arg.StartDate,
		arg.EndDate,
		arg.NextDue,
		arg.Description,
	)
	var i Recurring
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.ToAmount,
		&i.CategoryID,
		&i.Cadence,
		&i.IntervalN,
		&i.StartDate,
		&i.EndDate,
		&i.NextDue,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecurring = `-- name: DeleteRecurring :execrows
DELETE FROM recurring WHERE id = $1
`

func (q *Queries) DeleteRecurring(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecurring, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRecurring = `-- name: GetRecurring :one
SELECT id, type, from_account_id, to_account_id, amount, to_amount,
    category_id, cadence, interval_n, start_date, end_date, next_due, description, created_at
FROM recurring WHERE id = $1
`

func (q *Queries) GetRecurring(ctx context.Context, id int64) (Recurring, error) {
	row := q.db.QueryRow(ctx, getRecurring, id)
	var i Recurring
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.ToAmount,
		&i.CategoryID,
		&i.Cadence,
		&i.IntervalN,
		&i.StartDate,
		&i.EndDate,
		&i.NextDue,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRecurringForUpdate = `-- name: GetRecurringForUpdate :one
SELECT id, type, from_account_id, to_account_id, amount, to_amount,
    category_id, cadence, interval_n, start_date, end_date, next_due, description, created_at
FROM recurring WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRecurringForUpdate(ctx context.Context, id int64) (Recurring, error) {
	row := q.db.QueryRow(ctx, getRecurringForUpdate, id)
	var i Recurring
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.ToAmount,
		&i.CategoryID,
		&i.Cadence,
		&i.IntervalN,
		&i.StartDate,
		&i.EndDate,
		&i.NextDue,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listRecurring = `-- name: ListRecurring :many
SELECT
    r.id, r.type, r.from_account_id, r.to_account_id, r.amount, r.to_amount,
    r.category_id, r.cadence, r.interval_n, r.start_date, r.end_date, r.next_due,
    r.description, r.created_at,
    fa.name AS from_account_name, fa.currency AS from_currency,
    ta.name AS to_account_name, ta.currency AS to_currency,
    c.name AS category_name, c.kind AS category_kind
FROM recurring r
LEFT JOIN account fa ON fa.id = r.from_account_id
LEFT JOIN account ta ON ta.id = r.to_account_id
LEFT JOIN category c ON c.id = r.category_id
ORDER BY r.next_due, r.id
`

type ListRecurringRow struct {
	ID              int64
	Type            string
	FromAccountID   pgtype.Int8
	ToAccountID     pgtype.Int8
	Amount          decimal.Decimal
	ToAmount        decimal.Decimal
	CategoryID      pgtype.Int8
	Cadence         string
	IntervalN       int32
	StartDate       time.Time
	EndDate         pgtype.Date
	NextDue         time.Time
	Description     string
	CreatedAt       pgtype.Timestamptz
	FromAccountName pgtype.Text
	FromCurrency    pgtype.Text
	ToAccountName   pgtype.Text
	ToCurrency      pgtype.Text
	CategoryName    pgtype.Text
	CategoryKind    pgtype.Text
}

// Every template with its account and category names joined for display, ordered
// by next_due then id so the soonest-due surface first.
func (q *Queries) ListRecurring(ctx context.Context) ([]ListRecurringRow, error) {
	rows, err := q.db.Query(ctx, listRecurring)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringRow{}
	for rows.Next() {
		var i ListRecurringRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.ToAmount,
			&i.CategoryID,
			&i.Cadence,
			&i.IntervalN,
			&i.StartDate,
			&i.EndDate,
			&i.NextDue,
			&i.Description,
			&i.CreatedAt,
			&i.FromAccountName,
			&i.FromCurrency,
			&i.ToAccountName,
			&i.ToCurrency,
			&i.CategoryName,
			&i.CategoryKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurring = `-- name: UpdateRecurring :execrows
UPDATE recurring SET
    type = $2, from_account_id = $3, to_account_id = $4, amount = $5, to_amount = $6,
    category_id = $7, cadence = $8, interval_n = $9, start_date = $10, end_date = $11,
    next_due = $12, description = $13
WHERE id = $1
`

type UpdateRecurringParams struct {
	ID            int64
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	Amount        decimal.Decimal
	ToAmount      decimal.Decimal
	CategoryID    pgtype.Int8
	Cadence       string
	IntervalN     int32
	StartDate     time.Time
	EndDate       pgtype.Date
	NextDue       time.Time
	Description   string
}

func (q *Queries) UpdateRecurring(ctx context.Context, arg UpdateRecurringParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRecurring,
		arg.ID,
		arg.Type,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.ToAmount,
		arg.CategoryID,
		arg.Cadence,
		arg.IntervalN,
		arg.StartDate,
		arg.EndDate,
		arg.NextDue,
		arg.Description,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRecurringNextDue = `-- name: UpdateRecurringNextDue :execrows
UPDATE recurring SET next_due = $2 WHERE id = $1
`

type UpdateRecurringNextDueParams struct {
	ID      int64
	NextDue time.Time
}

func (q *Queries) UpdateRecurringNextDue(ctx context.Context, arg UpdateRecurringNextDueParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRecurringNextDue, arg.ID, arg.NextDue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
