// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: security.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSecurity = `-- name: CreateSecurity :one
INSERT INTO security (symbol, name, type, quote_currency, asset_category_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, symbol, name, type, quote_currency, created_at, asset_category_id
`

type CreateSecurityParams struct {
	Symbol          string
	Name            string
	Type            string
	QuoteCurrency   string
	AssetCategoryID pgtype.Int8
}

func (q *Queries) CreateSecurity(ctx context.Context, arg CreateSecurityParams) (Security, error) {
	row := q.db.QueryRow(ctx, createSecurity,
		arg.Symbol,
		arg.Name,
		arg.Type,
		arg.QuoteCurrency,
		arg.AssetCategoryID,
	)
	var i Security
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Type,
		&i.QuoteCurrency,
		&i.CreatedAt,
		&i.AssetCategoryID,
	)
	return i, err
}

const getSecurity = `-- name: GetSecurity :one
SELECT id, symbol, name, type, quote_currency, created_at, asset_category_id FROM security WHERE id = $1
`

func (q *Queries) GetSecurity(ctx context.Context, id int64) (Security, error) {
	row := q.db.QueryRow(ctx, getSecurity, id)
	var i Security
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Type,
		&i.QuoteCurrency,
		&i.CreatedAt,
		&i.AssetCategoryID,
	)
	return i, err
}

const getSecurityBySymbol = `-- name: GetSecurityBySymbol :one
SELECT id, symbol, name, type, quote_currency, created_at, asset_category_id FROM security WHERE symbol = $1
`

func (q *Queries) GetSecurityBySymbol(ctx context.Context, symbol string) (Security, error) {
	row := q.db.QueryRow(ctx, getSecurityBySymbol, symbol)
	var i Security
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Type,
		&i.QuoteCurrency,
		&i.CreatedAt,
		&i.AssetCategoryID,
	)
	return i, err
}

const listSecurities = `-- name: ListSecurities :many
SELECT id, symbol, name, type, quote_currency, created_at, asset_category_id FROM security ORDER BY symbol, id
`

func (q *Queries) ListSecurities(ctx context.Context) ([]Security, error) {
	rows, err := q.db.Query(ctx, listSecurities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Security{}
	for rows.Next() {
		var i Security
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.Type,
			&i.QuoteCurrency,
			&i.CreatedAt,
			&i.AssetCategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSecurityCategory = `-- name: SetSecurityCategory :execrows
UPDATE security SET asset_category_id = $2 WHERE id = $1
`

type SetSecurityCategoryParams struct {
	ID              int64
	AssetCategoryID pgtype.Int8
}

func (q *Queries) SetSecurityCategory(ctx context.Context, arg SetSecurityCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSecurityCategory, arg.ID, arg.AssetCategoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
