// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settings.sql

package store

import (
	"context"
)

const getDisplayCurrency = `-- name: GetDisplayCurrency :one
SELECT display_currency FROM app_settings WHERE id = TRUE
`

func (q *Queries) GetDisplayCurrency(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getDisplayCurrency)
	var display_currency string
	err := row.Scan(&display_currency)
	return display_currency, err
}

const setDisplayCurrency = `-- name: SetDisplayCurrency :exec
UPDATE app_settings SET display_currency = $1 WHERE id = TRUE
`

func (q *Queries) SetDisplayCurrency(ctx context.Context, displayCurrency string) error {
	_, err := q.db.Exec(ctx, setDisplayCurrency, displayCurrency)
	return err
}
