// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transaction.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transaction (type, from_account_id, to_account_id, from_amount, to_amount, occurred_on, description, category_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, type, from_account_id, to_account_id, from_amount, to_amount, occurred_on, description, created_at, category_id
`

type CreateTransactionParams struct {
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	FromAmount    decimal.Decimal
	ToAmount      decimal.Decimal
	OccurredOn    time.Time
	Description   string
	CategoryID    pgtype.Int8
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Type,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.FromAmount,
		arg.ToAmount,
		arg.OccurredOn,
		arg.Description,
		arg.CategoryID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.FromAmount,
		&i.ToAmount,
		&i.OccurredOn,
		&i.Description,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transaction WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAccountTransactions = `-- name: ListAccountTransactions :many
SELECT id, type, from_account_id, to_account_id, from_amount, to_amount, occurred_on, description, created_at, category_id
FROM transaction
WHERE from_account_id = $1 OR to_account_id = $1
ORDER BY occurred_on DESC, id DESC
`

func (q *Queries) ListAccountTransactions(ctx context.Context, fromAccountID pgtype.Int8) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listAccountTransactions, fromAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.FromAmount,
			&i.ToAmount,
			&i.OccurredOn,
			&i.Description,
			&i.CreatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :execrows
UPDATE transaction
SET type = $2, from_account_id = $3, to_account_id = $4, from_amount = $5, to_amount = $6, occurred_on = $7, description = $8, category_id = $9
WHERE id = $1
`

type UpdateTransactionParams struct {
	ID            int64
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	FromAmount    decimal.Decimal
	ToAmount      decimal.Decimal
	OccurredOn    time.Time
	Description   string
	CategoryID    pgtype.Int8
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTransaction,
		arg.ID,
		arg.Type,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.FromAmount,
		arg.ToAmount,
		arg.OccurredOn,
		arg.Description,
		arg.CategoryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
