// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transaction.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const addTransactionTag = `-- name: AddTransactionTag :exec
INSERT INTO transaction_tag (transaction_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTransactionTagParams struct {
	TransactionID int64
	TagID         int64
}

func (q *Queries) AddTransactionTag(ctx context.Context, arg AddTransactionTagParams) error {
	_, err := q.db.Exec(ctx, addTransactionTag, arg.TransactionID, arg.TagID)
	return err
}

const bulkSetCategory = `-- name: BulkSetCategory :execrows
UPDATE transaction SET category_id = $1 WHERE id = ANY($2::bigint[]) AND type = $3
`

type BulkSetCategoryParams struct {
	CategoryID pgtype.Int8
	Column2    []int64
	Type       string
}

// Assign one category to many transactions in a single statement (Story 10.1,
// one tx AD-3). The type guard scopes the write to rows matching the category's
// kind, so a transfer/trade id can never be categorized even if submitted.
func (q *Queries) BulkSetCategory(ctx context.Context, arg BulkSetCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkSetCategory, arg.CategoryID, arg.Column2, arg.Type)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createImportedTransaction = `-- name: CreateImportedTransaction :execrows
INSERT INTO transaction (type, from_account_id, to_account_id, from_amount, to_amount, occurred_on, description, import_hash, category_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateImportedTransactionParams struct {
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	FromAmount    decimal.Decimal
	ToAmount      decimal.Decimal
	OccurredOn    time.Time
	Description   string
	ImportHash    pgtype.Text
	CategoryID    pgtype.Int8
}

func (q *Queries) CreateImportedTransaction(ctx context.Context, arg CreateImportedTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createImportedTransaction,
		arg.Type,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.FromAmount,
		arg.ToAmount,
		arg.OccurredOn,
		arg.Description,
		arg.ImportHash,
		arg.CategoryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOFXTransaction = `-- name: CreateOFXTransaction :execrows
INSERT INTO transaction (type, from_account_id, to_account_id, from_amount, to_amount, occurred_on, description, fitid, category_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateOFXTransactionParams struct {
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	FromAmount    decimal.Decimal
	ToAmount      decimal.Decimal
	OccurredOn    time.Time
	Description   string
	Fitid         pgtype.Text
	CategoryID    pgtype.Int8
}

// OFX import (FR-16): an Income/Expense row carrying the bank's FITID (or NULL
// when the STMTTRN has none). category_id and import_hash default NULL — OFX
// dedup is FITID-only, never the tab importer's content hash.
func (q *Queries) CreateOFXTransaction(ctx context.Context, arg CreateOFXTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createOFXTransaction,
		arg.Type,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.FromAmount,
		arg.ToAmount,
		arg.OccurredOn,
		arg.Description,
		arg.Fitid,
		arg.CategoryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transaction (type, from_account_id, to_account_id, from_amount, to_amount, occurred_on, description, category_id, security_id, quantity, price, fees)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, type, from_account_id, to_account_id, from_amount, to_amount, occurred_on, description, created_at, category_id, import_hash, security_id, quantity, price, fees, fitid, note
`

type CreateTransactionParams struct {
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	FromAmount    decimal.Decimal
	ToAmount      decimal.Decimal
	OccurredOn    time.Time
	Description   string
	CategoryID    pgtype.Int8
	SecurityID    pgtype.Int8
	Quantity      decimal.Decimal
	Price         decimal.Decimal
	Fees          decimal.Decimal
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Type,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.FromAmount,
		arg.ToAmount,
		arg.OccurredOn,
		arg.Description,
		arg.CategoryID,
		arg.SecurityID,
		arg.Quantity,
		arg.Price,
		arg.Fees,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.FromAmount,
		&i.ToAmount,
		&i.OccurredOn,
		&i.Description,
		&i.CreatedAt,
		&i.CategoryID,
		&i.ImportHash,
		&i.SecurityID,
		&i.Quantity,
		&i.Price,
		&i.Fees,
		&i.Fitid,
		&i.Note,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transaction WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTransactionTags = `-- name: DeleteTransactionTags :exec
DELETE FROM transaction_tag WHERE transaction_id = $1
`

// Clear a transaction's tag links (the annotate use-case replaces the whole set).
func (q *Queries) DeleteTransactionTags(ctx context.Context, transactionID int64) error {
	_, err := q.db.Exec(ctx, deleteTransactionTags, transactionID)
	return err
}

const getTransaction = `-- name: GetTransaction :one

SELECT id, type, from_account_id, to_account_id, from_amount, to_amount, occurred_on, description, created_at, category_id, import_hash, security_id, quantity, price, fees, fitid, note
FROM transaction WHERE id = $1
`

// Notes & tags (Story 10.2 / FR-21). Presentation metadata only.
func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.FromAmount,
		&i.ToAmount,
		&i.OccurredOn,
		&i.Description,
		&i.CreatedAt,
		&i.CategoryID,
		&i.ImportHash,
		&i.SecurityID,
		&i.Quantity,
		&i.Price,
		&i.Fees,
		&i.Fitid,
		&i.Note,
	)
	return i, err
}

const listAccountFitids = `-- name: ListAccountFitids :many
SELECT fitid
FROM transaction
WHERE fitid IS NOT NULL AND (from_account_id = $1 OR to_account_id = $1)
`

func (q *Queries) ListAccountFitids(ctx context.Context, fromAccountID pgtype.Int8) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listAccountFitids, fromAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var fitid pgtype.Text
		if err := rows.Scan(&fitid); err != nil {
			return nil, err
		}
		items = append(items, fitid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountImportHashes = `-- name: ListAccountImportHashes :many
SELECT import_hash
FROM transaction
WHERE import_hash IS NOT NULL AND (from_account_id = $1 OR to_account_id = $1)
`

func (q *Queries) ListAccountImportHashes(ctx context.Context, fromAccountID pgtype.Int8) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listAccountImportHashes, fromAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var import_hash pgtype.Text
		if err := rows.Scan(&import_hash); err != nil {
			return nil, err
		}
		items = append(items, import_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountTransactions = `-- name: ListAccountTransactions :many
SELECT id, type, from_account_id, to_account_id, from_amount, to_amount, occurred_on, description, created_at, category_id, import_hash, security_id, quantity, price, fees, fitid, note
FROM transaction
WHERE from_account_id = $1 OR to_account_id = $1
ORDER BY occurred_on DESC, id DESC
`

func (q *Queries) ListAccountTransactions(ctx context.Context, fromAccountID pgtype.Int8) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listAccountTransactions, fromAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.FromAmount,
			&i.ToAmount,
			&i.OccurredOn,
			&i.Description,
			&i.CreatedAt,
			&i.CategoryID,
			&i.ImportHash,
			&i.SecurityID,
			&i.Quantity,
			&i.Price,
			&i.Fees,
			&i.Fitid,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTransactions = `-- name: ListTagsForTransactions :many
SELECT tt.transaction_id, t.name
FROM transaction_tag tt
JOIN tag t ON t.id = tt.tag_id
WHERE tt.transaction_id = ANY($1::bigint[])
ORDER BY tt.transaction_id, t.name
`

type ListTagsForTransactionsRow struct {
	TransactionID int64
	Name          string
}

// Tag names for many transactions at once (register/detail display), so the
// service maps them without an N+1 per row.
func (q *Queries) ListTagsForTransactions(ctx context.Context, dollar_1 []int64) ([]ListTagsForTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTagsForTransactions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForTransactionsRow{}
	for rows.Next() {
		var i ListTagsForTransactionsRow
		if err := rows.Scan(&i.TransactionID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionKindsByIDs = `-- name: ListTransactionKindsByIDs :many
SELECT id, type FROM transaction WHERE id = ANY($1::bigint[])
`

type ListTransactionKindsByIDsRow struct {
	ID   int64
	Type string
}

// The (id, type) of the given transactions, for validating a bulk-categorize
// selection (Story 10.1): every selected row must exist and be income/expense of
// the category's kind. Transfers/trades are returned with their type so the
// service can reject them (they are not categorizable, AD-9).
func (q *Queries) ListTransactionKindsByIDs(ctx context.Context, dollar_1 []int64) ([]ListTransactionKindsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionKindsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionKindsByIDsRow{}
	for rows.Next() {
		var i ListTransactionKindsByIDsRow
		if err := rows.Scan(&i.ID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionTags = `-- name: ListTransactionTags :many
SELECT t.id, t.name
FROM tag t
JOIN transaction_tag tt ON tt.tag_id = t.id
WHERE tt.transaction_id = $1
ORDER BY t.name
`

type ListTransactionTagsRow struct {
	ID   int64
	Name string
}

// One transaction's tag names, alphabetical (detail/edit view).
func (q *Queries) ListTransactionTags(ctx context.Context, transactionID int64) ([]ListTransactionTagsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionTags, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionTagsRow{}
	for rows.Next() {
		var i ListTransactionTagsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, type, from_account_id, to_account_id, from_amount, to_amount, occurred_on, description, created_at, category_id, import_hash, security_id, quantity, price, fees, fitid, note
FROM transaction
ORDER BY occurred_on DESC, id DESC
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.FromAmount,
			&i.ToAmount,
			&i.OccurredOn,
			&i.Description,
			&i.CreatedAt,
			&i.CategoryID,
			&i.ImportHash,
			&i.SecurityID,
			&i.Quantity,
			&i.Price,
			&i.Fees,
			&i.Fitid,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionNote = `-- name: SetTransactionNote :execrows
UPDATE transaction SET note = $2 WHERE id = $1
`

type SetTransactionNoteParams struct {
	ID   int64
	Note string
}

func (q *Queries) SetTransactionNote(ctx context.Context, arg SetTransactionNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTransactionNote, arg.ID, arg.Note)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTransaction = `-- name: UpdateTransaction :execrows
UPDATE transaction
SET type = $2, from_account_id = $3, to_account_id = $4, from_amount = $5, to_amount = $6, occurred_on = $7, description = $8, category_id = $9
WHERE id = $1
`

type UpdateTransactionParams struct {
	ID            int64
	Type          string
	FromAccountID pgtype.Int8
	ToAccountID   pgtype.Int8
	FromAmount    decimal.Decimal
	ToAmount      decimal.Decimal
	OccurredOn    time.Time
	Description   string
	CategoryID    pgtype.Int8
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTransaction,
		arg.ID,
		arg.Type,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.FromAmount,
		arg.ToAmount,
		arg.OccurredOn,
		arg.Description,
		arg.CategoryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tag (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

// Create-on-use: return the tag whether it already existed or is newly inserted.
func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
